#include "fonts.hpp"

// const uint8_t Numbers[] = {
//     0xfc, 0x8c, 0x8c, 0x94, 0xa4, 0xc4, 0xc4, 0xfc,  // 0
//     0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c,  // 1
//     0xfc, 0xfc, 0xc0, 0xfc, 0xfc, 0x0c, 0xfc, 0xfc,  // 2
//     0xfc, 0xfc, 0x0c, 0x3c, 0x3c, 0x0c, 0xfc, 0xfc,  // 3
//     0x0c, 0x0c, 0x0c, 0xfc, 0xfc, 0xcc, 0xcc, 0xcc,  // 4
//     0xfc, 0xfc, 0x0c, 0xfc, 0xfc, 0xc0, 0xfc, 0xfc,  // 5
//     0xfc, 0xcc, 0xcc, 0xfc, 0xfc, 0xc0, 0xfc, 0xfc,  // 6
//     0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0xfc, 0xfc,  // 7
//     0xfc, 0xcc, 0xcc, 0xfc, 0xfc, 0xcc, 0xcc, 0xfc,  // 8
//     0xfc, 0xfc, 0x0c, 0xfc, 0xfc, 0xcc, 0xcc, 0xfc,  // 9
// };

// /* Font information for Numbers */
// FontDef_t Numbers_6x8 =
// {
//     6, /*  Width, in pixels, of space character */
//     8, /*  Character height */
//     Numbers, /*  Character bitmap array */
// };

const uint8_t Numbers[] = {
    
    //██████
    //██∙∙∙█
    //██∙∙∙█
    //█∙█∙∙█
    //█∙∙█∙█
    //█∙∙∙██
    //█∙∙∙██
    //██████
    0xfc, 
    0x8c, 
    0x8c, 
    0x94, 
    0xa4, 
    0xc4, 
    0xc4, 
    0xfc,

    //∙∙∙∙∙█
    //∙∙∙∙∙█
    //∙∙∙∙∙█
    //∙∙∙∙∙█
    //∙∙∙∙∙█
    //∙∙∙∙∙█
    //∙∙∙∙∙█
    //∙∙∙∙∙█
    0x04, 
    0x04, 
    0x04, 
    0x04, 
    0x04, 
    0x04, 
    0x04, 
    0x04,

    //██████
    //∙∙∙∙∙█
    //∙∙∙∙∙█
    //██████
    //█∙∙∙∙∙
    //█∙∙∙∙∙
    //█∙∙∙∙∙
    //██████
    0xfc, 
    0x80, 
    0x80, 
    0x80, 
    0xfc, 
    0x04, 
    0x04, 
    0xfc,

    //██████
    //∙∙∙∙∙█
    //∙∙∙∙∙█
    //∙∙████
    //∙∙∙∙∙█
    //∙∙∙∙∙█
    //∙∙∙∙∙█
    //██████
    0xfc, 
    0x04, 
    0x04, 
    0x04, 
    0x3c, 
    0x04, 
    0x04, 
    0xfc,

    //█∙∙∙∙█
    //█∙∙∙∙█
    //█∙∙∙∙█
    //█∙∙∙∙█
    //██████
    //∙∙∙∙∙█
    //∙∙∙∙∙█
    //∙∙∙∙∙█
    0x04, 
    0x04, 
    0x04, 
    0xfc, 
    0x84, 
    0x84, 
    0x84, 
    0x84,

    //██████
    //█∙∙∙∙∙
    //█∙∙∙∙∙
    //██████
    //∙∙∙∙∙█
    //∙∙∙∙∙█
    //∙∙∙∙∙█
    //██████
    0xfc, 
    0x04, 
    0x04, 
    0x04, 
    0xfc, 
    0x80, 
    0x80, 
    0xfc,

    //██████
    //█∙∙∙∙∙
    //█∙∙∙∙∙
    //██████
    //█∙∙∙∙█
    //█∙∙∙∙█
    //█∙∙∙∙█
    //██████
    0xfc, 
    0x84, 
    0x84, 
    0x84, 
    0xfc, 
    0x80, 
    0x80, 
    0xfc,

    //██████
    //∙∙∙∙∙█
    //∙∙∙∙∙█
    //∙∙∙∙∙█
    //∙∙∙∙∙█
    //∙∙∙∙∙█
    //∙∙∙∙∙█
    //∙∙∙∙∙█
    0x04, 
    0x04, 
    0x04, 
    0x04, 
    0x04, 
    0x04, 
    0x04, 
    0xfc,

    //██████
    //█∙∙∙∙█
    //█∙∙∙∙█
    //█∙∙∙∙█
    //██████
    //█∙∙∙∙█
    //█∙∙∙∙█
    //██████
    0xfc, 
    0x84, 
    0x84, 
    0xfc, 
    0x84, 
    0x84, 
    0x84, 
    0xfc,

    //██████
    //█∙∙∙∙█
    //█∙∙∙∙█
    //█∙∙∙∙█
    //██████
    //∙∙∙∙∙█
    //∙∙∙∙∙█
    //██████
    0xfc, 
    0x04, 
    0x04, 
    0xfc, 
    0x84, 
    0x84, 
    0x84, 
    0xfc,

};

/* Font information for Numbers */
FontDef_t Numbers_6x8 =
{
    6, /*  Width, in pixels, of space character */
    8, /*  Character height */
    Numbers, /*  Character bitmap array */
};

/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* font
* filename: C:/Users/domko/OneDrive/Pulpit/lcd-image-converter/New folder/Arial10_c.xml
* name: Arial10_c
* family: Arial
* size: 10
* style: Regular
* included characters:  !"#$%&'()*+,-./0123456789:;<=>?\x0040ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~
* antialiasing: no
* type: proportional
* encoding: UTF-8
* unicode bom: no
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Threshold Dither 0
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: bottom_to_top
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/




static const uint8_t image_data_Arial10_c_0x20[8] = {
        // character: ' '
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00
};
static const tImage Arial10_c_0x20 = { image_data_Arial10_c_0x20,
                                       3, 8, 8};

static const uint8_t image_data_Arial10_c_0x21[8] = {
        // character: '!'
        0x40,
        0x00,
        0x40,
        0x40,
        0x40,
        0x40,
        0x40,
        0x00
};
static const tImage Arial10_c_0x21 = { image_data_Arial10_c_0x21,
                                       3, 8, 8};

static const uint8_t image_data_Arial10_c_0x22[8] = {
        // character: '"'
        0x00,
        0x00,
        0x00,
        0x00,
        0xa0,
        0xa0,
        0xa0,
        0x00
};
static const tImage Arial10_c_0x22 = { image_data_Arial10_c_0x22,
                                       3, 8, 8};

static const uint8_t image_data_Arial10_c_0x23[8] = {
        // character: '#'
        0xa0,
        0xa0,
        0xf8,
        0x50,
        0xf8,
        0x28,
        0x28,
        0x00
};
static const tImage Arial10_c_0x23 = { image_data_Arial10_c_0x23,
                                       5, 8, 8};

static const uint8_t image_data_Arial10_c_0x24[8] = {
        // character: '$'
        0x70,
        0xa8,
        0x28,
        0x38,
        0xe0,
        0xa8,
        0x70,
        0x00
};
static const tImage Arial10_c_0x24 = { image_data_Arial10_c_0x24,
                                       5, 8, 8};

static const uint8_t image_data_Arial10_c_0x25[8] = {
        // character: '%'
        0x24,
        0x2a,
        0x1a,
        0x54,
        0xa8,
        0xa8,
        0x44,
        0x00
};
static const tImage Arial10_c_0x25 = { image_data_Arial10_c_0x25,
                                       7, 8, 8};

static const uint8_t image_data_Arial10_c_0x26[8] = {
        // character: '&'
        0x76,
        0x8c,
        0x96,
        0x60,
        0x30,
        0x48,
        0x38,
        0x00
};
static const tImage Arial10_c_0x26 = { image_data_Arial10_c_0x26,
                                       7, 8, 8};

static const uint8_t image_data_Arial10_c_0x27[8] = {
        // character: '''
        0x00,
        0x00,
        0x00,
        0x00,
        0x80,
        0x80,
        0x80,
        0x00
};
static const tImage Arial10_c_0x27 = { image_data_Arial10_c_0x27,
                                       2, 8, 8};

static const uint8_t image_data_Arial10_c_0x28[8] = {
        // character: '('
        0x20,
        0x40,
        0x80,
        0x80,
        0x80,
        0x40,
        0x20,
        0x00
};
static const tImage Arial10_c_0x28 = { image_data_Arial10_c_0x28,
                                       3, 8, 8};

static const uint8_t image_data_Arial10_c_0x29[8] = {
        // character: ')'
        0x80,
        0x40,
        0x20,
        0x20,
        0x20,
        0x40,
        0x80,
        0x00
};
static const tImage Arial10_c_0x29 = { image_data_Arial10_c_0x29,
                                       3, 8, 8};

static const uint8_t image_data_Arial10_c_0x2a[8] = {
        // character: '*'
        0x00,
        0x00,
        0x00,
        0x00,
        0xa0,
        0x40,
        0xe0,
        0x00
};
static const tImage Arial10_c_0x2a = { image_data_Arial10_c_0x2a,
                                       3, 8, 8};

static const uint8_t image_data_Arial10_c_0x2b[8] = {
        // character: '+'
        0x00,
        0x20,
        0x20,
        0xf8,
        0x20,
        0x20,
        0x00,
        0x00
};
static const tImage Arial10_c_0x2b = { image_data_Arial10_c_0x2b,
                                       5, 8, 8};

static const uint8_t image_data_Arial10_c_0x2c[8] = {
        // character: ','
        0x40,
        0x40,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00
};
static const tImage Arial10_c_0x2c = { image_data_Arial10_c_0x2c,
                                       3, 8, 8};

static const uint8_t image_data_Arial10_c_0x2d[8] = {
        // character: '-'
        0x00,
        0x00,
        0xe0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00
};
static const tImage Arial10_c_0x2d = { image_data_Arial10_c_0x2d,
                                       3, 8, 8};

static const uint8_t image_data_Arial10_c_0x2e[8] = {
        // character: '.'
        0x40,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00
};
static const tImage Arial10_c_0x2e = { image_data_Arial10_c_0x2e,
                                       3, 8, 8};

static const uint8_t image_data_Arial10_c_0x2f[8] = {
        // character: '/'
        0x80,
        0x80,
        0x40,
        0x40,
        0x40,
        0x20,
        0x20,
        0x00
};
static const tImage Arial10_c_0x2f = { image_data_Arial10_c_0x2f,
                                       3, 8, 8};

static const uint8_t image_data_Arial10_c_0x30[8] = {
        // character: '0'
        0x70,
        0x88,
        0x88,
        0x88,
        0x88,
        0x88,
        0x70,
        0x00
};
static const tImage Arial10_c_0x30 = { image_data_Arial10_c_0x30,
                                       5, 8, 8};

static const uint8_t image_data_Arial10_c_0x31[8] = {
        // character: '1'
        0x20,
        0x20,
        0x20,
        0x20,
        0xa0,
        0x60,
        0x20,
        0x00
};
static const tImage Arial10_c_0x31 = { image_data_Arial10_c_0x31,
                                       3, 8, 8};

static const uint8_t image_data_Arial10_c_0x32[8] = {
        // character: '2'
        0xf8,
        0x40,
        0x20,
        0x10,
        0x08,
        0x88,
        0x70,
        0x00
};
static const tImage Arial10_c_0x32 = { image_data_Arial10_c_0x32,
                                       5, 8, 8};

static const uint8_t image_data_Arial10_c_0x33[8] = {
        // character: '3'
        0x70,
        0x88,
        0x08,
        0x30,
        0x08,
        0x88,
        0x70,
        0x00
};
static const tImage Arial10_c_0x33 = { image_data_Arial10_c_0x33,
                                       5, 8, 8};

static const uint8_t image_data_Arial10_c_0x34[8] = {
        // character: '4'
        0x08,
        0x08,
        0xfc,
        0x88,
        0x48,
        0x28,
        0x18,
        0x00
};
static const tImage Arial10_c_0x34 = { image_data_Arial10_c_0x34,
                                       6, 8, 8};

static const uint8_t image_data_Arial10_c_0x35[8] = {
        // character: '5'
        0x70,
        0x88,
        0x08,
        0x88,
        0xf0,
        0x40,
        0x78,
        0x00
};
static const tImage Arial10_c_0x35 = { image_data_Arial10_c_0x35,
                                       5, 8, 8};

static const uint8_t image_data_Arial10_c_0x36[8] = {
        // character: '6'
        0x70,
        0x88,
        0x88,
        0x88,
        0xf0,
        0x88,
        0x70,
        0x00
};
static const tImage Arial10_c_0x36 = { image_data_Arial10_c_0x36,
                                       5, 8, 8};

static const uint8_t image_data_Arial10_c_0x37[8] = {
        // character: '7'
        0x40,
        0x40,
        0x20,
        0x20,
        0x10,
        0x10,
        0xf8,
        0x00
};
static const tImage Arial10_c_0x37 = { image_data_Arial10_c_0x37,
                                       5, 8, 8};

static const uint8_t image_data_Arial10_c_0x38[8] = {
        // character: '8'
        0x70,
        0x88,
        0x88,
        0x70,
        0x88,
        0x88,
        0x70,
        0x00
};
static const tImage Arial10_c_0x38 = { image_data_Arial10_c_0x38,
                                       5, 8, 8};

static const uint8_t image_data_Arial10_c_0x39[8] = {
        // character: '9'
        0x70,
        0x88,
        0x78,
        0x88,
        0x88,
        0x88,
        0x70,
        0x00
};
static const tImage Arial10_c_0x39 = { image_data_Arial10_c_0x39,
                                       5, 8, 8};

static const uint8_t image_data_Arial10_c_0x3a[8] = {
        // character: ':'
        0x40,
        0x00,
        0x00,
        0x00,
        0x40,
        0x00,
        0x00,
        0x00
};
static const tImage Arial10_c_0x3a = { image_data_Arial10_c_0x3a,
                                       3, 8, 8};

static const uint8_t image_data_Arial10_c_0x3b[8] = {
        // character: ';'
        0x40,
        0x40,
        0x00,
        0x00,
        0x40,
        0x00,
        0x00,
        0x00
};
static const tImage Arial10_c_0x3b = { image_data_Arial10_c_0x3b,
                                       3, 8, 8};

static const uint8_t image_data_Arial10_c_0x3c[8] = {
        // character: '<'
        0x00,
        0x10,
        0x60,
        0x80,
        0x60,
        0x10,
        0x00,
        0x00
};
static const tImage Arial10_c_0x3c = { image_data_Arial10_c_0x3c,
                                       4, 8, 8};

static const uint8_t image_data_Arial10_c_0x3d[8] = {
        // character: '='
        0x00,
        0x00,
        0xf8,
        0x00,
        0xf8,
        0x00,
        0x00,
        0x00
};
static const tImage Arial10_c_0x3d = { image_data_Arial10_c_0x3d,
                                       5, 8, 8};

static const uint8_t image_data_Arial10_c_0x3e[8] = {
        // character: '>'
        0x00,
        0x80,
        0x60,
        0x10,
        0x60,
        0x80,
        0x00,
        0x00
};
static const tImage Arial10_c_0x3e = { image_data_Arial10_c_0x3e,
                                       4, 8, 8};

static const uint8_t image_data_Arial10_c_0x3f[8] = {
        // character: '?'
        0x10,
        0x00,
        0x10,
        0x18,
        0x04,
        0x84,
        0x78,
        0x00
};
static const tImage Arial10_c_0x3f = { image_data_Arial10_c_0x3f,
                                       6, 8, 8};

static const uint8_t image_data_Arial10_c_0x40[8] = {
        // character: '\x0040'
        0x3e,
        0x41,
        0x9e,
        0xa5,
        0xa6,
        0x9a,
        0x41,
        0x3e
};
static const tImage Arial10_c_0x40 = { image_data_Arial10_c_0x40,
                                       8, 8, 8};

static const uint8_t image_data_Arial10_c_0x41[8] = {
        // character: 'A'
        0x88,
        0x88,
        0xf8,
        0x88,
        0x50,
        0x50,
        0x20,
        0x00
};
static const tImage Arial10_c_0x41 = { image_data_Arial10_c_0x41,
                                       5, 8, 8};

static const uint8_t image_data_Arial10_c_0x42[8] = {
        // character: 'B'
        0xf0,
        0x88,
        0x88,
        0xf8,
        0x88,
        0x88,
        0xf0,
        0x00
};
static const tImage Arial10_c_0x42 = { image_data_Arial10_c_0x42,
                                       5, 8, 8};

static const uint8_t image_data_Arial10_c_0x43[8] = {
        // character: 'C'
        0x70,
        0x88,
        0x80,
        0x80,
        0x80,
        0x88,
        0x70,
        0x00
};
static const tImage Arial10_c_0x43 = { image_data_Arial10_c_0x43,
                                       5, 8, 8};

static const uint8_t image_data_Arial10_c_0x44[8] = {
        // character: 'D'
        0xe0,
        0x90,
        0x88,
        0x88,
        0x88,
        0x90,
        0xe0,
        0x00
};
static const tImage Arial10_c_0x44 = { image_data_Arial10_c_0x44,
                                       5, 8, 8};

static const uint8_t image_data_Arial10_c_0x45[8] = {
        // character: 'E'
        0xf8,
        0x80,
        0x80,
        0xf8,
        0x80,
        0x80,
        0xf8,
        0x00
};
static const tImage Arial10_c_0x45 = { image_data_Arial10_c_0x45,
                                       5, 8, 8};

static const uint8_t image_data_Arial10_c_0x46[8] = {
        // character: 'F'
        0x80,
        0x80,
        0x80,
        0xe0,
        0x80,
        0x80,
        0xf0,
        0x00
};
static const tImage Arial10_c_0x46 = { image_data_Arial10_c_0x46,
                                       4, 8, 8};

static const uint8_t image_data_Arial10_c_0x47[8] = {
        // character: 'G'
        0x30,
        0x48,
        0x84,
        0x9c,
        0x80,
        0x48,
        0x30,
        0x00
};
static const tImage Arial10_c_0x47 = { image_data_Arial10_c_0x47,
                                       6, 8, 8};

static const uint8_t image_data_Arial10_c_0x48[8] = {
        // character: 'H'
        0x88,
        0x88,
        0x88,
        0xf8,
        0x88,
        0x88,
        0x88,
        0x00
};
static const tImage Arial10_c_0x48 = { image_data_Arial10_c_0x48,
                                       5, 8, 8};

static const uint8_t image_data_Arial10_c_0x49[8] = {
        // character: 'I'
        0x40,
        0x40,
        0x40,
        0x40,
        0x40,
        0x40,
        0x40,
        0x00
};
static const tImage Arial10_c_0x49 = { image_data_Arial10_c_0x49,
                                       3, 8, 8};

static const uint8_t image_data_Arial10_c_0x4a[8] = {
        // character: 'J'
        0xe0,
        0x90,
        0x10,
        0x10,
        0x10,
        0x10,
        0x10,
        0x00
};
static const tImage Arial10_c_0x4a = { image_data_Arial10_c_0x4a,
                                       4, 8, 8};

static const uint8_t image_data_Arial10_c_0x4b[8] = {
        // character: 'K'
        0x84,
        0x88,
        0xd0,
        0xa0,
        0x90,
        0x88,
        0x84,
        0x00
};
static const tImage Arial10_c_0x4b = { image_data_Arial10_c_0x4b,
                                       6, 8, 8};

static const uint8_t image_data_Arial10_c_0x4c[8] = {
        // character: 'L'
        0xf8,
        0x80,
        0x80,
        0x80,
        0x80,
        0x80,
        0x80,
        0x00
};
static const tImage Arial10_c_0x4c = { image_data_Arial10_c_0x4c,
                                       5, 8, 8};

static const uint8_t image_data_Arial10_c_0x4d[8] = {
        // character: 'M'
        0x92,
        0xaa,
        0xaa,
        0xaa,
        0xc6,
        0xc6,
        0x82,
        0x00
};
static const tImage Arial10_c_0x4d = { image_data_Arial10_c_0x4d,
                                       7, 8, 8};

static const uint8_t image_data_Arial10_c_0x4e[8] = {
        // character: 'N'
        0x88,
        0x98,
        0x98,
        0xa8,
        0xc8,
        0xc8,
        0x88,
        0x00
};
static const tImage Arial10_c_0x4e = { image_data_Arial10_c_0x4e,
                                       5, 8, 8};

static const uint8_t image_data_Arial10_c_0x4f[8] = {
        // character: 'O'
        0x78,
        0x84,
        0x84,
        0x84,
        0x84,
        0x84,
        0x78,
        0x00
};
static const tImage Arial10_c_0x4f = { image_data_Arial10_c_0x4f,
                                       6, 8, 8};

static const uint8_t image_data_Arial10_c_0x50[8] = {
        // character: 'P'
        0x80,
        0x80,
        0x80,
        0xf0,
        0x88,
        0x88,
        0xf0,
        0x00
};
static const tImage Arial10_c_0x50 = { image_data_Arial10_c_0x50,
                                       5, 8, 8};

static const uint8_t image_data_Arial10_c_0x51[8] = {
        // character: 'Q'
        0x7c,
        0x98,
        0x84,
        0x84,
        0x84,
        0x84,
        0x78,
        0x00
};
static const tImage Arial10_c_0x51 = { image_data_Arial10_c_0x51,
                                       6, 8, 8};

static const uint8_t image_data_Arial10_c_0x52[8] = {
        // character: 'R'
        0x88,
        0x88,
        0x90,
        0xf0,
        0x88,
        0x88,
        0xf0,
        0x00
};
static const tImage Arial10_c_0x52 = { image_data_Arial10_c_0x52,
                                       5, 8, 8};

static const uint8_t image_data_Arial10_c_0x53[8] = {
        // character: 'S'
        0x70,
        0x88,
        0x08,
        0x70,
        0x80,
        0x88,
        0x70,
        0x00
};
static const tImage Arial10_c_0x53 = { image_data_Arial10_c_0x53,
                                       5, 8, 8};

static const uint8_t image_data_Arial10_c_0x54[8] = {
        // character: 'T'
        0x20,
        0x20,
        0x20,
        0x20,
        0x20,
        0x20,
        0xf8,
        0x00
};
static const tImage Arial10_c_0x54 = { image_data_Arial10_c_0x54,
                                       5, 8, 8};

static const uint8_t image_data_Arial10_c_0x55[8] = {
        // character: 'U'
        0x70,
        0x88,
        0x88,
        0x88,
        0x88,
        0x88,
        0x88,
        0x00
};
static const tImage Arial10_c_0x55 = { image_data_Arial10_c_0x55,
                                       5, 8, 8};

static const uint8_t image_data_Arial10_c_0x56[8] = {
        // character: 'V'
        0x10,
        0x28,
        0x28,
        0x44,
        0x44,
        0x44,
        0x82,
        0x00
};
static const tImage Arial10_c_0x56 = { image_data_Arial10_c_0x56,
                                       7, 8, 8};

static const uint8_t image_data_Arial10_c_0x57[8] = {
        // character: 'W'
        0x44,
        0xaa,
        0xaa,
        0xaa,
        0xaa,
        0xaa,
        0x92,
        0x00
};
static const tImage Arial10_c_0x57 = { image_data_Arial10_c_0x57,
                                       7, 8, 8};

static const uint8_t image_data_Arial10_c_0x58[8] = {
        // character: 'X'
        0x82,
        0x44,
        0x28,
        0x10,
        0x28,
        0x44,
        0x82,
        0x00
};
static const tImage Arial10_c_0x58 = { image_data_Arial10_c_0x58,
                                       7, 8, 8};

static const uint8_t image_data_Arial10_c_0x59[8] = {
        // character: 'Y'
        0x10,
        0x10,
        0x10,
        0x10,
        0x28,
        0x44,
        0x82,
        0x00
};
static const tImage Arial10_c_0x59 = { image_data_Arial10_c_0x59,
                                       7, 8, 8};

static const uint8_t image_data_Arial10_c_0x5a[8] = {
        // character: 'Z'
        0xfc,
        0x80,
        0x40,
        0x20,
        0x10,
        0x08,
        0xfc,
        0x00
};
static const tImage Arial10_c_0x5a = { image_data_Arial10_c_0x5a,
                                       6, 8, 8};

static const uint8_t image_data_Arial10_c_0x5b[8] = {
        // character: '['
        0xc0,
        0x80,
        0x80,
        0x80,
        0x80,
        0x80,
        0xc0,
        0x00
};
static const tImage Arial10_c_0x5b = { image_data_Arial10_c_0x5b,
                                       2, 8, 8};

static const uint8_t image_data_Arial10_c_0x5c[8] = {
        // character: '\'
        0x20,
        0x20,
        0x40,
        0x40,
        0x40,
        0x80,
        0x80,
        0x00
};
static const tImage Arial10_c_0x5c = { image_data_Arial10_c_0x5c,
                                       3, 8, 8};

static const uint8_t image_data_Arial10_c_0x5d[8] = {
        // character: ']'
        0xc0,
        0x40,
        0x40,
        0x40,
        0x40,
        0x40,
        0xc0,
        0x00
};
static const tImage Arial10_c_0x5d = { image_data_Arial10_c_0x5d,
                                       2, 8, 8};

static const uint8_t image_data_Arial10_c_0x5e[8] = {
        // character: '^'
        0x00,
        0x00,
        0x00,
        0x88,
        0x50,
        0x50,
        0x20,
        0x00
};
static const tImage Arial10_c_0x5e = { image_data_Arial10_c_0x5e,
                                       5, 8, 8};

static const uint8_t image_data_Arial10_c_0x5f[8] = {
        // character: '_'
        0xf0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00
};
static const tImage Arial10_c_0x5f = { image_data_Arial10_c_0x5f,
                                       4, 8, 8};

static const uint8_t image_data_Arial10_c_0x60[8] = {
        // character: '`'
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x40,
        0x80,
        0x00
};
static const tImage Arial10_c_0x60 = { image_data_Arial10_c_0x60,
                                       2, 8, 8};

static const uint8_t image_data_Arial10_c_0x61[8] = {
        // character: 'a'
        0xf0,
        0x90,
        0x70,
        0x10,
        0x70,
        0x00,
        0x00,
        0x00
};
static const tImage Arial10_c_0x61 = { image_data_Arial10_c_0x61,
                                       4, 8, 8};

static const uint8_t image_data_Arial10_c_0x62[8] = {
        // character: 'b'
        0xe0,
        0x90,
        0x90,
        0x90,
        0xe0,
        0x80,
        0x80,
        0x00
};
static const tImage Arial10_c_0x62 = { image_data_Arial10_c_0x62,
                                       4, 8, 8};

static const uint8_t image_data_Arial10_c_0x63[8] = {
        // character: 'c'
        0x60,
        0x90,
        0x80,
        0x90,
        0x60,
        0x00,
        0x00,
        0x00
};
static const tImage Arial10_c_0x63 = { image_data_Arial10_c_0x63,
                                       4, 8, 8};

static const uint8_t image_data_Arial10_c_0x64[8] = {
        // character: 'd'
        0x70,
        0x90,
        0x90,
        0x90,
        0x70,
        0x10,
        0x10,
        0x00
};
static const tImage Arial10_c_0x64 = { image_data_Arial10_c_0x64,
                                       4, 8, 8};

static const uint8_t image_data_Arial10_c_0x65[8] = {
        // character: 'e'
        0x70,
        0x80,
        0xf0,
        0x90,
        0x60,
        0x00,
        0x00,
        0x00
};
static const tImage Arial10_c_0x65 = { image_data_Arial10_c_0x65,
                                       4, 8, 8};

static const uint8_t image_data_Arial10_c_0x66[8] = {
        // character: 'f'
        0x40,
        0x40,
        0x40,
        0x40,
        0xe0,
        0x40,
        0x20,
        0x00
};
static const tImage Arial10_c_0x66 = { image_data_Arial10_c_0x66,
                                       3, 8, 8};

static const uint8_t image_data_Arial10_c_0x67[8] = {
        // character: 'g'
        0x60,
        0x90,
        0x70,
        0x90,
        0x90,
        0x60,
        0x00,
        0x00
};
static const tImage Arial10_c_0x67 = { image_data_Arial10_c_0x67,
                                       4, 8, 8};

static const uint8_t image_data_Arial10_c_0x68[8] = {
        // character: 'h'
        0x90,
        0x90,
        0x90,
        0x90,
        0xe0,
        0x80,
        0x80,
        0x00
};
static const tImage Arial10_c_0x68 = { image_data_Arial10_c_0x68,
                                       4, 8, 8};

static const uint8_t image_data_Arial10_c_0x69[8] = {
        // character: 'i'
        0x40,
        0x40,
        0x40,
        0x40,
        0x40,
        0x00,
        0x40,
        0x00
};
static const tImage Arial10_c_0x69 = { image_data_Arial10_c_0x69,
                                       3, 8, 8};

static const uint8_t image_data_Arial10_c_0x6a[8] = {
        // character: 'j'
        0xc0,
        0x40,
        0x40,
        0x40,
        0x40,
        0x00,
        0x40,
        0x00
};
static const tImage Arial10_c_0x6a = { image_data_Arial10_c_0x6a,
                                       2, 8, 8};

static const uint8_t image_data_Arial10_c_0x6b[8] = {
        // character: 'k'
        0x90,
        0xa0,
        0xe0,
        0xa0,
        0x90,
        0x80,
        0x80,
        0x00
};
static const tImage Arial10_c_0x6b = { image_data_Arial10_c_0x6b,
                                       4, 8, 8};

static const uint8_t image_data_Arial10_c_0x6c[8] = {
        // character: 'l'
        0x40,
        0x40,
        0x40,
        0x40,
        0x40,
        0x40,
        0x40,
        0x00
};
static const tImage Arial10_c_0x6c = { image_data_Arial10_c_0x6c,
                                       3, 8, 8};

static const uint8_t image_data_Arial10_c_0x6d[8] = {
        // character: 'm'
        0x92,
        0x92,
        0x92,
        0x92,
        0xfc,
        0x00,
        0x00,
        0x00
};
static const tImage Arial10_c_0x6d = { image_data_Arial10_c_0x6d,
                                       7, 8, 8};

static const uint8_t image_data_Arial10_c_0x6e[8] = {
        // character: 'n'
        0x90,
        0x90,
        0x90,
        0x90,
        0xe0,
        0x00,
        0x00,
        0x00
};
static const tImage Arial10_c_0x6e = { image_data_Arial10_c_0x6e,
                                       4, 8, 8};

static const uint8_t image_data_Arial10_c_0x6f[8] = {
        // character: 'o'
        0x60,
        0x90,
        0x90,
        0x90,
        0x60,
        0x00,
        0x00,
        0x00
};
static const tImage Arial10_c_0x6f = { image_data_Arial10_c_0x6f,
                                       4, 8, 8};

static const uint8_t image_data_Arial10_c_0x70[8] = {
        // character: 'p'
        0x80,
        0xe0,
        0x90,
        0x90,
        0xe0,
        0x00,
        0x00,
        0x00
};
static const tImage Arial10_c_0x70 = { image_data_Arial10_c_0x70,
                                       4, 8, 8};

static const uint8_t image_data_Arial10_c_0x71[8] = {
        // character: 'q'
        0x10,
        0x70,
        0x90,
        0x90,
        0x70,
        0x00,
        0x00,
        0x00
};
static const tImage Arial10_c_0x71 = { image_data_Arial10_c_0x71,
                                       4, 8, 8};

static const uint8_t image_data_Arial10_c_0x72[8] = {
        // character: 'r'
        0x80,
        0x80,
        0x80,
        0x80,
        0xc0,
        0x00,
        0x00,
        0x00
};
static const tImage Arial10_c_0x72 = { image_data_Arial10_c_0x72,
                                       2, 8, 8};

static const uint8_t image_data_Arial10_c_0x73[8] = {
        // character: 's'
        0xe0,
        0x10,
        0x60,
        0x80,
        0x70,
        0x00,
        0x00,
        0x00
};
static const tImage Arial10_c_0x73 = { image_data_Arial10_c_0x73,
                                       4, 8, 8};

static const uint8_t image_data_Arial10_c_0x74[8] = {
        // character: 't'
        0x60,
        0x40,
        0x40,
        0x40,
        0xe0,
        0x40,
        0x40,
        0x00
};
static const tImage Arial10_c_0x74 = { image_data_Arial10_c_0x74,
                                       3, 8, 8};

static const uint8_t image_data_Arial10_c_0x75[8] = {
        // character: 'u'
        0x70,
        0x90,
        0x90,
        0x90,
        0x90,
        0x00,
        0x00,
        0x00
};
static const tImage Arial10_c_0x75 = { image_data_Arial10_c_0x75,
                                       4, 8, 8};

static const uint8_t image_data_Arial10_c_0x76[8] = {
        // character: 'v'
        0x20,
        0x50,
        0x50,
        0x50,
        0x88,
        0x00,
        0x00,
        0x00
};
static const tImage Arial10_c_0x76 = { image_data_Arial10_c_0x76,
                                       5, 8, 8};

static const uint8_t image_data_Arial10_c_0x77[8] = {
        // character: 'w'
        0x44,
        0xaa,
        0xaa,
        0xaa,
        0x92,
        0x00,
        0x00,
        0x00
};
static const tImage Arial10_c_0x77 = { image_data_Arial10_c_0x77,
                                       7, 8, 8};

static const uint8_t image_data_Arial10_c_0x78[8] = {
        // character: 'x'
        0x88,
        0x50,
        0x20,
        0x50,
        0x88,
        0x00,
        0x00,
        0x00
};
static const tImage Arial10_c_0x78 = { image_data_Arial10_c_0x78,
                                       5, 8, 8};

static const uint8_t image_data_Arial10_c_0x79[8] = {
        // character: 'y'
        0x40,
        0x20,
        0x50,
        0x50,
        0x88,
        0x00,
        0x00,
        0x00
};
static const tImage Arial10_c_0x79 = { image_data_Arial10_c_0x79,
                                       5, 8, 8};

static const uint8_t image_data_Arial10_c_0x7a[8] = {
        // character: 'z'
        0xf8,
        0x40,
        0x20,
        0x10,
        0xf8,
        0x00,
        0x00,
        0x00
};
static const tImage Arial10_c_0x7a = { image_data_Arial10_c_0x7a,
                                       5, 8, 8};

static const uint8_t image_data_Arial10_c_0x7b[8] = {
        // character: '{'
        0x60,
        0x40,
        0x40,
        0x80,
        0x40,
        0x40,
        0x60,
        0x00
};
static const tImage Arial10_c_0x7b = { image_data_Arial10_c_0x7b,
                                       3, 8, 8};

static const uint8_t image_data_Arial10_c_0x7c[8] = {
        // character: '|'
        0x40,
        0x40,
        0x40,
        0x40,
        0x40,
        0x40,
        0x40,
        0x00
};
static const tImage Arial10_c_0x7c = { image_data_Arial10_c_0x7c,
                                       3, 8, 8};

static const uint8_t image_data_Arial10_c_0x7d[8] = {
        // character: '}'
        0xc0,
        0x40,
        0x40,
        0x20,
        0x40,
        0x40,
        0xc0,
        0x00
};
static const tImage Arial10_c_0x7d = { image_data_Arial10_c_0x7d,
                                       3, 8, 8};

static const uint8_t image_data_Arial10_c_0x7e[8] = {
        // character: '~'
        0x00,
        0x00,
        0xb8,
        0xe8,
        0x00,
        0x00,
        0x00,
        0x00
};
static const tImage Arial10_c_0x7e = { image_data_Arial10_c_0x7e,
                                       5, 8, 8};


static const tChar Arial10_c_array[] = {

        // character: ' '
        {0x20, &Arial10_c_0x20},

        // character: '!'
        {0x21, &Arial10_c_0x21},

        // character: '"'
        {0x22, &Arial10_c_0x22},

        // character: '#'
        {0x23, &Arial10_c_0x23},

        // character: '$'
        {0x24, &Arial10_c_0x24},

        // character: '%'
        {0x25, &Arial10_c_0x25},

        // character: '&'
        {0x26, &Arial10_c_0x26},

        // character: '''
        {0x27, &Arial10_c_0x27},

        // character: '('
        {0x28, &Arial10_c_0x28},

        // character: ')'
        {0x29, &Arial10_c_0x29},

        // character: '*'
        {0x2a, &Arial10_c_0x2a},

        // character: '+'
        {0x2b, &Arial10_c_0x2b},

        // character: ','
        {0x2c, &Arial10_c_0x2c},

        // character: '-'
        {0x2d, &Arial10_c_0x2d},

        // character: '.'
        {0x2e, &Arial10_c_0x2e},

        // character: '/'
        {0x2f, &Arial10_c_0x2f},

        // character: '0'
        {0x30, &Arial10_c_0x30},

        // character: '1'
        {0x31, &Arial10_c_0x31},

        // character: '2'
        {0x32, &Arial10_c_0x32},

        // character: '3'
        {0x33, &Arial10_c_0x33},

        // character: '4'
        {0x34, &Arial10_c_0x34},

        // character: '5'
        {0x35, &Arial10_c_0x35},

        // character: '6'
        {0x36, &Arial10_c_0x36},

        // character: '7'
        {0x37, &Arial10_c_0x37},

        // character: '8'
        {0x38, &Arial10_c_0x38},

        // character: '9'
        {0x39, &Arial10_c_0x39},

        // character: ':'
        {0x3a, &Arial10_c_0x3a},

        // character: ';'
        {0x3b, &Arial10_c_0x3b},

        // character: '<'
        {0x3c, &Arial10_c_0x3c},

        // character: '='
        {0x3d, &Arial10_c_0x3d},

        // character: '>'
        {0x3e, &Arial10_c_0x3e},

        // character: '?'
        {0x3f, &Arial10_c_0x3f},

        // character: '\x0040'
        {0x40, &Arial10_c_0x40},

        // character: 'A'
        {0x41, &Arial10_c_0x41},

        // character: 'B'
        {0x42, &Arial10_c_0x42},

        // character: 'C'
        {0x43, &Arial10_c_0x43},

        // character: 'D'
        {0x44, &Arial10_c_0x44},

        // character: 'E'
        {0x45, &Arial10_c_0x45},

        // character: 'F'
        {0x46, &Arial10_c_0x46},

        // character: 'G'
        {0x47, &Arial10_c_0x47},

        // character: 'H'
        {0x48, &Arial10_c_0x48},

        // character: 'I'
        {0x49, &Arial10_c_0x49},

        // character: 'J'
        {0x4a, &Arial10_c_0x4a},

        // character: 'K'
        {0x4b, &Arial10_c_0x4b},

        // character: 'L'
        {0x4c, &Arial10_c_0x4c},

        // character: 'M'
        {0x4d, &Arial10_c_0x4d},

        // character: 'N'
        {0x4e, &Arial10_c_0x4e},

        // character: 'O'
        {0x4f, &Arial10_c_0x4f},

        // character: 'P'
        {0x50, &Arial10_c_0x50},

        // character: 'Q'
        {0x51, &Arial10_c_0x51},

        // character: 'R'
        {0x52, &Arial10_c_0x52},

        // character: 'S'
        {0x53, &Arial10_c_0x53},

        // character: 'T'
        {0x54, &Arial10_c_0x54},

        // character: 'U'
        {0x55, &Arial10_c_0x55},

        // character: 'V'
        {0x56, &Arial10_c_0x56},

        // character: 'W'
        {0x57, &Arial10_c_0x57},

        // character: 'X'
        {0x58, &Arial10_c_0x58},

        // character: 'Y'
        {0x59, &Arial10_c_0x59},

        // character: 'Z'
        {0x5a, &Arial10_c_0x5a},

        // character: '['
        {0x5b, &Arial10_c_0x5b},

        // character: '\'
        {0x5c, &Arial10_c_0x5c},

        // character: ']'
        {0x5d, &Arial10_c_0x5d},

        // character: '^'
        {0x5e, &Arial10_c_0x5e},

        // character: '_'
        {0x5f, &Arial10_c_0x5f},

        // character: '`'
        {0x60, &Arial10_c_0x60},

        // character: 'a'
        {0x61, &Arial10_c_0x61},

        // character: 'b'
        {0x62, &Arial10_c_0x62},

        // character: 'c'
        {0x63, &Arial10_c_0x63},

        // character: 'd'
        {0x64, &Arial10_c_0x64},

        // character: 'e'
        {0x65, &Arial10_c_0x65},

        // character: 'f'
        {0x66, &Arial10_c_0x66},

        // character: 'g'
        {0x67, &Arial10_c_0x67},

        // character: 'h'
        {0x68, &Arial10_c_0x68},

        // character: 'i'
        {0x69, &Arial10_c_0x69},

        // character: 'j'
        {0x6a, &Arial10_c_0x6a},

        // character: 'k'
        {0x6b, &Arial10_c_0x6b},

        // character: 'l'
        {0x6c, &Arial10_c_0x6c},

        // character: 'm'
        {0x6d, &Arial10_c_0x6d},

        // character: 'n'
        {0x6e, &Arial10_c_0x6e},

        // character: 'o'
        {0x6f, &Arial10_c_0x6f},

        // character: 'p'
        {0x70, &Arial10_c_0x70},

        // character: 'q'
        {0x71, &Arial10_c_0x71},

        // character: 'r'
        {0x72, &Arial10_c_0x72},

        // character: 's'
        {0x73, &Arial10_c_0x73},

        // character: 't'
        {0x74, &Arial10_c_0x74},

        // character: 'u'
        {0x75, &Arial10_c_0x75},

        // character: 'v'
        {0x76, &Arial10_c_0x76},

        // character: 'w'
        {0x77, &Arial10_c_0x77},

        // character: 'x'
        {0x78, &Arial10_c_0x78},

        // character: 'y'
        {0x79, &Arial10_c_0x79},

        // character: 'z'
        {0x7a, &Arial10_c_0x7a},

        // character: '{'
        {0x7b, &Arial10_c_0x7b},

        // character: '|'
        {0x7c, &Arial10_c_0x7c},

        // character: '}'
        {0x7d, &Arial10_c_0x7d},

        // character: '~'
        {0x7e, &Arial10_c_0x7e}

};


const tFont Arial10_c = { 95, Arial10_c_array };

// /* Font information for Arial10_c */
// FontDef_t Arial10_c_5x8 =
// {
//     5, /*  Width, in pixels, of space character */
//     8, /*  Character height */
//     Arial10_c, /*  Character bitmap array */
// };
